/// Falso JSON con informacion estatica

let todasLasBicicletas = [
  {
    "id": 1,
    "name": "Bici Fast",
    "description": "Esta esta buenisima.",
    "detail": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat ab quas ex suscipi quasi autem nesciunt delectus esse rem sit inventore expedita magni recusan exercitationem quod, quam, labore rerum commodi!",
    "image": "./Imgs/bici1.jpg",
    "price": 62000,
    "count": 1,
  },
  {
    "id": 2,
    "name": "Bici Cool",
    "description": "Lo que buscabas.",
    "detail": "Lore ipsum dolor sit, amet consectetur adipisicing elit. Rem veritatis autem ullam voluptatum consectetur! Natus possimus, praesentium deserunt unde iure aperiam tempora tenetur. Minus modi sapiente optio deserunt! Laudantium, fuga?",
    "image": "./Imgs/bici4.jpg",
    "price": 45000,
    "count": 1,
  },
  {
    "id": 3,
    "name": "Bici Nieve",
    "description": "Uauuuu para esquiar al mismo tiempo.",
    "detail": " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque aliquam minus sit est inventore facilis nisi, culpa fuga ipsa ratione. Reprehenderit saepe est dolorem, fuga a quisquam autem eaque. Ex!",
    "image": "./Imgs/bici5.jpg",
    "price": 50000,
    "count": 1,
  },
  {
    "id": 4,
    "name": "Bici Carrera",
    "description": "No lleges mas tarde al trabajo!",
    "detail": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet aliquid, at harum voluptatum voluptas voluptates iusto itaque debitis consectetur incidunt corrupti accusamus, ad expedita maxime saepe numquam obcaecati, veniam ex.",
    "image": "./Imgs/bici2.jpg",
    "price": 38000,
    "count": 1,
  },
  {
    "id": 5,
    "name": "Bici Ciudad",
    "description": "Recorrete toda la city tranki.",
    "detail": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor ipsa quia sunt quo iste iure, itaque cupiditate, voluptatibus modi obcaecati nemo laborum nobis quidem officiis animi aperiam labore veniam saepe.",
    "image": "./Imgs/bici13.jpg",
    "price": 40000,
    "count": 1,
  },
  {
    "id": 6,
    "name": "Bici Montaña",
    "description": "Para tus travesias mas extremas",
    "detail": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti officia aspernatur exercitationem provident eaque rem ex quibusdam est iusto hic, quidem ea optio saepe adipisci, nulla ab voluptates debitis recusandae.",
    "image": "./Imgs/bici12.jpg",
    "price": 58000,
    "count": 1,
  },
  {
    "id": 7,
    "name": "Bici Ejecutiva",
    "description": "Liviana y facil de andar",
    "detail": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti quos adipisci illum cumque voluptas? Minus asperiores qui amet quia molestiae. Quam velit optio quasi doloribus accusamus error consectetur sed recusandae.",
    "image": "./Imgs/bici15.jpg",
    "price": 32000,
    "count": 1,
  },
  {
    "id": 8,
    "name": "Bici Power",
    "description": "Esta esta on fire.",
    "detail": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi eveniet sequi assumenda voluptatibus similique. Totam assumenda iusto doloribus corrupti sunt nesciunt expedita repudiandae magnam vitae dolorem, magni vel, alias modi.",
    "image": "./Imgs/bici14.jpg",
    "price": 60000,
    "count": 1,
  },
];
