
let todasLasBicicletas = [
  {
    id: 1,
    name: "Bici Fast",
    description: "Esta esta buenisima.",
    image: "./Imgs/bici1.jpg",
    price: 62000,
    count: 1,
  },
  {
    id: 2,
    name: "Bici Cool",
    description: "  Lo que buscabas.",
    image: "./Imgs/bici4.jpg",
    price: 45000,
    count: 1,
  },
  {
    id: 3,
    name: "Bici Nieve",
    description: "Uauuuu para esquiar al mismo tiempo.",
    image: "./Imgs/bici5.jpg",
    price: 50000,
    count: 1,
  },
  {
    id: 4,
    name: "Bici Carrera",
    description: "No lleges mas tarde al trabajo!",
    image: "./Imgs/bici2.jpg",
    price: 38000,
    count: 1,
  },
  {
    id: 5,
    name: "Bici Ciudad",
    description: "Recorrete toda la city tranki.",
    image: "./Imgs/bici13.jpg",
    price: 40000,
    count: 1,
  },
  {
    id: 6,
    name: "Bici Montaña",
    description: "Para tus travesias mas extremas",
    image: "./Imgs/bici12.jpg",
    price: 58000,
    count: 1,
  },
  {
    id: 7,
    name: "Bici Ejecutiva",
    description: "Liviana y facil de andar",
    image: "./Imgs/bici15.jpg",
    price: 32000,
    count: 1,
  },
  {
    id: 8,
    name: "Bici Power",
    description: "Esta esta on fire.",
    image: "./Imgs/bici14.jpg",
    price: 60000,
    count: 1,
  },
];